
FROM node:20.17.0-alpine AS base

RUN apk add --no-cache

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --frozen-lockfile

FROM base AS build

COPY . .

RUN npx prisma generate 

RUN ls -la node_modules/@prisma

CMD ["npm", "run" , "start:dev"]


