
FROM node:20.17.0-alpine AS base

RUN npm install -g @nestjs/cli

RUN apk add --no-cache

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install 

FROM base AS build

COPY . .

RUN npx prisma generate 

RUN ls -la node_modules/@prisma
CMD ["npm", "run", "start:dev"]





